### ISSUE TITLE
test

### ISSUE THREAD

**Issue by martin-lysk** [martin-lysk/isomorphic-git#2]
### Todos without Issue Reference:

<details open >
  <summary><code>src</code></summary><blockquote>
<details open style="padding-left:30px">
  <summary><code>api</code></summary>

* [ ] [`add.js:76`](https://github.com/martin-lysk/isomorphic-git/blob/b9465b09617fd7cfdc7adb14f2f6104ba5d6342f/src/api/add.js#L76): TODO: Should ignore UNLESS it's already in the index. 
* [ ] [`commit.js:34`](https://github.com/martin-lysk/isomorphic-git/blob/b9465b09617fd7cfdc7adb14f2f6104ba5d6342f/src/api/commit.js#L34) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; TODO: fix it so it can expand branch names without throwing if the branch doesn't exist yet.\) 
* [ ] [`statusMatrix.js:246`](https://github.com/martin-lysk/isomorphic-git/blob/b9465b09617fd7cfdc7adb14f2f6104ba5d6342f/src/api/statusMatrix.js#L246): TODO: update this logic to handle N trees instead of just 3. 

</details>
<blockquote></details>
1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890
